[project]
name = "cycleflattener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "docplex>=2.31.254",
    "numpy>=2.2.6",
    "pip>=26.0",
    "scipy>=1.15.3",
]


[tool.uv]
package = true

[tool.uv.workspace]
members = [
    ".",
    ".",
]

[tool.uv.sources]
cycleflattener = { workspace = true }

[dependency-groups]
dev = [
    "cycleflattener",
]
