[project]
name = "cycleflattener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = [
    "cplex",
    "docplex>=2.31.254",
    "networkx>=3.4.2",
    "numpy>=2.2.6",
    "pip>=26.0",
    "scipy>=1.15.3",
]


[tool.uv]
package = true

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
cycleflattener = { workspace = true }
cplex = { path = "cplex_python_3.10" }

[dependency-groups]
dev = [
    "cycleflattener",
]
